.TH MIDORI "1" "September 2007" "midori 0.0.6" "User commands"

.SH NAME
midori \- fast and lightweight web browser

.SH SYNOPSIS
.PP
\fBmidori\fR [OPTION...] [URL]

.SH DESCRIPTION
\fBmidori\fR is a lightweight web browser.

.SH OPTIONS
.IP
.SS "Application Options:"
.TP
\fB\-v\fR, \fB\-\-version\fR
Display program version
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use

.SS "Help Options:"
.TP
\-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options

.SH REPORTING BUGS
Please report comments, suggestions and bugs to christian@twotoasts.de
.PP
Check for new versions at: http://software.twotoasts.de

.SH AUTHOR
\fBMidori\fR is copyright (C) 2007 Christian Dywan.
.PP
This manual page was written by Emanuele Rocca <ema@debian.org> for
the Debian GNU/Linux system (but may be used by others).
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 2 or any later version published
by the Free Software Foundation.
